/* Словари свободного ввода планировщика — по одному на язык.
   Собраны и проверены отдельно: каждый словарь писал носитель-агент, затем
   второй агент пытался его сломать выдуманными фразами. Термин ищется как
   ПОДСТРОКА, поэтому стемы («водопад» ловит «водопады»), и поэтому же ни один
   термин не должен встречаться внутри постороннего слова.
   Числа сюда не входят: суммы и длительность разбирает js/parse.js. */
var SB_LEXICON = {
 "zh": {
  "interests": {
   "sea": [
    "海滩",
    "沙滩",
    "海边",
    "大海",
    "看海",
    "海岛",
    "出海",
    "跳岛",
    "浮潜",
    "潜水",
    "深潜",
    "下海",
    "海龟",
    "珊瑚",
    "蝠鲼",
    "快艇",
    "坐船",
    "佩尼达",
    "蓝梦岛",
    "吉利岛"
   ],
   "nature": [
    "瀑布",
    "梯田",
    "稻田",
    "火山",
    "丛林",
    "雨林",
    "森林",
    "大自然",
    "徒步",
    "爬山",
    "登山",
    "日出",
    "温泉",
    "山谷",
    "田园",
    "猴子",
    "溪流",
    "巴图尔",
    "金塔马尼"
   ],
   "culture": [
    "寺庙",
    "神庙",
    "庙宇",
    "海神庙",
    "文化",
    "传统",
    "民俗",
    "当地人",
    "当地生活",
    "市场",
    "集市",
    "美食",
    "宗教",
    "仪式",
    "祭祀",
    "舞蹈",
    "手工艺",
    "历史",
    "风俗",
    "巴厘风情"
   ],
   "relax": [
    "放松",
    "休息",
    "躺平",
    "躺着",
    "发呆",
    "什么都不做",
    "什么都不想干",
    "摆烂",
    "spa",
    "水疗",
    "按摩",
    "泳池",
    "度假",
    "疗愈",
    "安静",
    "清静",
    "悠闲",
    "慢节奏",
    "瑜伽",
    "睡到自然醒"
   ],
   "adventure": [
    "漂流",
    "冲浪",
    "学冲浪",
    "冲浪板",
    "atv",
    "沙滩车",
    "越野",
    "越野车",
    "蹦极",
    "攀岩",
    "溪降",
    "滑索",
    "丛林飞跃",
    "滑翔伞",
    "摩托艇",
    "刺激",
    "肾上腺素",
    "冒险",
    "探险",
    "极限运动"
   ],
   "beauty": [
    "风景",
    "景色",
    "美景",
    "风光",
    "好看",
    "漂亮",
    "绝美",
    "拍照",
    "出片",
    "打卡",
    "网红",
    "机位",
    "小红书",
    "ins风",
    "摄影",
    "日落",
    "夕阳",
    "落日",
    "观景",
    "秋千"
   ]
  },
  "area": {
   "canggu": [
    "canggu",
    "changgu",
    "长谷",
    "苍古",
    "苍谷",
    "昌谷",
    "张谷",
    "巴图博隆",
    "布拉旺",
    "芬斯海滩"
   ],
   "seminyak": [
    "seminyak",
    "seminyk",
    "水明漾",
    "水明漾区",
    "水明漾海滩",
    "塞米亚克",
    "斯米亚克",
    "塞米尼亚克",
    "西米亚克",
    "谢米亚克"
   ],
   "ubud": [
    "ubud",
    "乌布",
    "乌布区",
    "乌布镇",
    "乌布皇宫",
    "德格拉朗",
    "特格拉朗",
    "泰加拉朗",
    "圣泉寺",
    "猴子森林",
    "圣猴森林",
    "阿勇河"
   ],
   "uluwatu": [
    "uluwatu",
    "ulu watu",
    "乌鲁瓦图",
    "乌鲁瓦土",
    "乌鲁瓦度",
    "乌鲁瓦图寺",
    "情人崖",
    "巴东巴东",
    "帕当帕当",
    "蓝点教堂",
    "苏鲁班"
   ],
   "nusa_dua": [
    "nusa dua",
    "nusadua",
    "努沙杜瓦",
    "努萨杜瓦",
    "奴沙杜瓦",
    "努沙度瓦",
    "努沙杜瓦海滩",
    "南湾",
    "丹戎贝诺阿",
    "贝诺阿"
   ],
   "sanur": [
    "sanur",
    "沙努尔",
    "萨努尔",
    "桑努尔",
    "莎努尔",
    "沙奴尔",
    "沙努",
    "沙努尔海滩",
    "萨努尔海滩",
    "沙努尔区"
   ],
   "jimbaran": [
    "jimbaran",
    "jimbalan",
    "金巴兰",
    "津巴兰",
    "京巴兰",
    "吉姆巴兰",
    "金巴兰海滩",
    "金巴兰沙滩",
    "金巴兰湾",
    "金巴兰海鲜"
   ],
   "kuta_legian": [
    "kuta",
    "kuta beach",
    "库塔",
    "库达",
    "库塔海滩",
    "库塔沙滩",
    "库塔区",
    "legian",
    "雷吉安",
    "莱吉安",
    "勒吉安",
    "力吉安"
   ]
  },
  "group": {
   "couple": [
    "情侣",
    "蜜月",
    "度蜜月",
    "蜜月旅行",
    "男朋友",
    "女朋友",
    "男友",
    "女友",
    "老公",
    "老婆",
    "对象",
    "未婚夫",
    "未婚妻",
    "求婚",
    "婚纱照",
    "结婚纪念日",
    "二人世界",
    "谈恋爱",
    "情人节"
   ],
   "family": [
    "家人",
    "一家人",
    "全家",
    "带娃",
    "遛娃",
    "带孩子",
    "孩子",
    "小孩",
    "宝宝",
    "婴儿",
    "儿童",
    "爸妈",
    "父母",
    "我妈",
    "老人",
    "长辈",
    "亲子",
    "亲子游",
    "三口",
    "四口"
   ],
   "friends": [
    "和朋友",
    "跟朋友",
    "朋友们",
    "朋友一起",
    "几个朋友",
    "一帮朋友",
    "一群朋友",
    "闺蜜",
    "姐妹们",
    "姐妹",
    "兄弟",
    "同学",
    "同事",
    "小伙伴",
    "死党",
    "基友",
    "结伴",
    "团建"
   ],
   "solo": [
    "一个人",
    "一个人去",
    "一个人玩",
    "自己一个人",
    "就我一个",
    "我自己",
    "独自",
    "独自一人",
    "独自旅行",
    "独游",
    "独行",
    "一人游",
    "单人",
    "单身",
    "solo"
   ]
  },
  "budget": {
   "low": [
    "便宜",
    "便宜点",
    "省钱",
    "穷游",
    "穷游党",
    "预算有限",
    "预算不多",
    "低预算",
    "经济型",
    "平价",
    "实惠",
    "学生党",
    "青旅",
    "背包客",
    "不想花太多",
    "花钱少",
    "50美元以内",
    "50刀以内",
    "300块以内",
    "200块"
   ],
   "mid": [
    "中等",
    "中档",
    "中端",
    "中等预算",
    "预算适中",
    "性价比",
    "不太贵",
    "不用太贵",
    "四星",
    "四星级",
    "普通酒店",
    "小资",
    "100美元",
    "100刀",
    "100美元左右",
    "一天100",
    "50到120",
    "50-120"
   ],
   "high": [
    "豪华",
    "奢华",
    "五星",
    "五星级",
    "高端",
    "顶级",
    "私人泳池",
    "泳池别墅",
    "独栋别墅",
    "私人别墅",
    "管家",
    "米其林",
    "不差钱",
    "预算充足",
    "高预算",
    "贵一点也没关系",
    "200美元",
    "300美元",
    "品质游"
   ]
  },
  "dayWords": [
   "住几晚",
   "几天",
   "多少天",
   "天",
   "待几天",
   "日游",
   "晚"
  ],
  "weekWords": [
   "一周",
   "三周",
   "两周",
   "个星期",
   "周末",
   "星期",
   "礼拜"
  ]
 },
 "en": {
  "interests": {
   "sea": [
    "beach",
    "ocean",
    "snorkel",
    "scuba",
    "diving",
    "swim",
    "island",
    "boat",
    "sailing",
    "cruise",
    "reef",
    "coral",
    "seaside",
    "turtle",
    "manta",
    "gili",
    "nusa penida"
   ],
   "nature": [
    "waterfall",
    "rice terrace",
    "rice field",
    "rice paddy",
    "jungle",
    "volcan",
    "mountain",
    "hike",
    "hiking",
    "trek",
    "nature",
    "forest",
    "sunrise",
    "wildlife",
    "national park",
    "lake",
    "batur",
    "monkey forest"
   ],
   "culture": [
    "temple",
    "ceremon",
    "cultur",
    "tradition",
    "local life",
    "local food",
    "local people",
    "village",
    "balinese",
    "hindu",
    "kecak",
    "histor",
    "museum",
    "market",
    "warung",
    "cooking class",
    "authentic",
    "tanah lot",
    "ritual",
    "babi guling"
   ],
   "relax": [
    "relax",
    "chill",
    "unwind",
    "massage",
    "spa day",
    "honeymoon",
    "wellness",
    "retreat",
    "quiet",
    "calm",
    "peaceful",
    "do nothing",
    "doing nothing",
    "lazy",
    "pool",
    "yoga",
    "meditat",
    "recharge",
    "no plans",
    "slow pace"
   ],
   "adventure": [
    "adventur",
    "rafting",
    "atv",
    "quad bike",
    "surf",
    "adrenaline",
    "climb",
    "off-road",
    "offroad",
    "zipline",
    "canyoning",
    "bungee",
    "paraglid",
    "extreme sport",
    "thrill",
    "kayak",
    "cliff jump",
    "white water"
   ],
   "beauty": [
    "beautiful",
    "beauty",
    "scenery",
    "scenic",
    "landscape",
    "photo",
    "instagram",
    "picture",
    "panoram",
    "sunset",
    "aesthetic",
    "stunning",
    "breathtaking",
    "gorgeous",
    "selfie",
    "viewpoint",
    "nice view",
    "great view",
    "amazing view",
    "bali swing"
   ]
  },
  "area": {
   "canggu": [
    "canggu",
    "cangu",
    "changgu",
    "changu",
    "canggo",
    "kanggu",
    "berawa",
    "batu bolong",
    "echo beach",
    "pererenan"
   ],
   "seminyak": [
    "seminyak",
    "seminiak",
    "seminyac",
    "semynyak",
    "siminyak",
    "petitenget",
    "oberoi",
    "double six",
    "batu belig",
    "kerobokan",
    "umalas"
   ],
   "ubud": [
    "ubud",
    "ubad",
    "ubod",
    "obud",
    "tegalalang",
    "tegallalang",
    "campuhan",
    "penestanan",
    "sayan",
    "peliatan"
   ],
   "uluwatu": [
    "uluwatu",
    "ulluwatu",
    "ulu watu",
    "uluwato",
    "pecatu",
    "bingin",
    "padang padang",
    "balangan",
    "dreamland",
    "suluban",
    "ungasan"
   ],
   "nusa_dua": [
    "nusa dua",
    "nusadua",
    "nusa-dua",
    "nusa doa",
    "tanjung benoa",
    "benoa",
    "sawangan",
    "geger beach",
    "btdc"
   ],
   "sanur": [
    "sanur",
    "sanoor",
    "sanure",
    "sanurr",
    "semawang",
    "sindhu",
    "mertasari",
    "batu jimbar"
   ],
   "jimbaran": [
    "jimbaran",
    "jimberan",
    "jimbaren",
    "jinbaran",
    "jimbran",
    "kedonganan",
    "muaya",
    "gwk",
    "fish market"
   ],
   "kuta_legian": [
    "kuta",
    "kutta",
    "legian",
    "legien",
    "leggian",
    "tuban",
    "poppies",
    "waterbom",
    "beachwalk"
   ]
  },
  "group": {
   "couple": [
    "couples",
    "as a couple",
    "we are a couple",
    "my wife",
    "my husband",
    "girlfriend",
    "boyfriend",
    "honeymoon",
    "romantic",
    "romance",
    "anniversary",
    "two of us",
    "my partner",
    "fiance",
    "just us two"
   ],
   "family": [
    "family",
    "families",
    "kids",
    "children",
    "child friendly",
    "kid friendly",
    "family friendly",
    "my son",
    "my daughter",
    "our son",
    "our daughter",
    "toddler",
    "baby",
    "teenager",
    "grandparents",
    "stroller"
   ],
   "friends": [
    "friends",
    "my friend",
    "a friend",
    "group of friends",
    "friend group",
    "buddies",
    "my mates",
    "with mates",
    "bachelor party",
    "bachelorette",
    "hen party",
    "hen weekend",
    "stag do",
    "girls trip",
    "guys trip",
    "boys trip"
   ],
   "solo": [
    "solo",
    "alone",
    "myself",
    "just me",
    "on my own",
    "only me",
    "one person",
    "1 person",
    "single traveller",
    "single traveler"
   ]
  },
  "budget": {
   "low": [
    "cheap",
    "budget trip",
    "on a budget",
    "low budget",
    "tight budget",
    "budget friendly",
    "backpack",
    "hostel",
    "homestay",
    "guesthouse",
    "affordable",
    "inexpensive",
    "low cost",
    "save money",
    "shoestring",
    "dorm",
    "under $50",
    "under 50"
   ],
   "mid": [
    "mid-range",
    "mid range",
    "midrange",
    "mid budget",
    "moderate",
    "comfortable",
    "reasonable",
    "average budget",
    "medium budget",
    "middle budget",
    "standard hotel",
    "3 star",
    "3-star",
    "three star",
    "4 star",
    "four star",
    "decent hotel",
    "not too expensive"
   ],
   "high": [
    "luxur",
    "5 star",
    "5-star",
    "five star",
    "high end",
    "high-end",
    "premium",
    "upscale",
    "splurge",
    "private villa",
    "pool villa",
    "private pool",
    "fine dining",
    "exclusive",
    "first class",
    "money is not an issue",
    "no budget limit",
    "over 200"
   ]
  },
  "dayWords": [
   "a few days",
   "day",
   "days",
   "fortnight",
   "night",
   "nights",
   "ten days"
  ],
  "weekWords": [
   "a week",
   "long weekend",
   "one week",
   "three weeks",
   "two weeks",
   "week",
   "weekend",
   "weeks"
  ]
 },
 "es": {
  "interests": {
   "sea": [
    "playa",
    "en el mar",
    "al mar",
    "snorkel",
    "esnorkel",
    "snorquel",
    "buceo",
    "bucear",
    "nadar",
    "islas",
    "nusa penida",
    "islas gili",
    "barco",
    "catamarán",
    "beach club",
    "tomar el sol",
    "cristalin",
    "arena blanca"
   ],
   "nature": [
    "cascada",
    "catarata",
    "arrozal",
    "campos de arroz",
    "terrazas de arroz",
    "selva",
    "jungla",
    "volcán",
    "volcan",
    "batur",
    "amanecer",
    "naturaleza",
    "senderismo",
    "caminata",
    "montaña",
    "bosque",
    "los monos",
    "aire libre",
    "tegalalang"
   ],
   "culture": [
    "templo",
    "ceremonia",
    "cultura",
    "tradicion",
    "tradición",
    "mercado",
    "gastronomía",
    "gastronomia",
    "comida local",
    "comida típica",
    "comida tipica",
    "pueblo",
    "vida local",
    "costumbres",
    "artesanía",
    "artesania",
    "kecak",
    "ofrendas",
    "balines",
    "museo"
   ],
   "relax": [
    "relaj",
    "descans",
    "tranquil",
    "no hacer nada",
    "sin prisas",
    "desconectar",
    "masaje",
    "spas",
    "un spa",
    "al spa",
    "piscina",
    "alberca",
    "hamaca",
    "yoga",
    "bienestar",
    "silenci",
    "sin estrés",
    "sin estres",
    "tumbar",
    "sin planes"
   ],
   "adventure": [
    "aventur",
    "adrenalina",
    "rafting",
    "surf",
    "quad",
    "atv",
    "escalada",
    "escalar",
    "tirolina",
    "tirolesa",
    "parapente",
    "trekking",
    "puenting",
    "kayak",
    "off road",
    "offroad",
    "4x4",
    "deportes extremos",
    "barranquismo",
    "canyoning"
   ],
   "beauty": [
    "las vistas",
    "buenas vistas",
    "vistas bonitas",
    "con vistas",
    "paisaje",
    "atardecer",
    "puesta de sol",
    "foto",
    "instagram",
    "panorámica",
    "panoramica",
    "mirador",
    "postal",
    "bonit",
    "precioso",
    "preciosa",
    "columpio",
    "de ensueño",
    "espectacular",
    "puerta del cielo"
   ]
  },
  "area": {
   "canggu": [
    "canggu",
    "canggú",
    "changgu",
    "changu",
    "kanggu",
    "canngu",
    "berawa",
    "pererenan",
    "batu bolong",
    "echo beach"
   ],
   "seminyak": [
    "seminyak",
    "seminyac",
    "seminiak",
    "seminyk",
    "semynyak",
    "petitenget",
    "kerobokan",
    "double six",
    "batubelig",
    "oberoi"
   ],
   "ubud": [
    "ubud",
    "úbud",
    "ubúd",
    "ubut",
    "monkey forest",
    "campuhan",
    "penestanan",
    "payangan",
    "kedewatan",
    "sayan"
   ],
   "uluwatu": [
    "uluwatu",
    "ulu watu",
    "uluwatú",
    "uluwato",
    "uluwattu",
    "bingin",
    "padang padang",
    "pecatu",
    "suluban",
    "balangan",
    "dreamland",
    "bukit"
   ],
   "nusa_dua": [
    "nusa dua",
    "nusadua",
    "nusa-dua",
    "nusa duá",
    "nusa duo",
    "nussa dua",
    "benoa",
    "sawangan",
    "geger",
    "btdc"
   ],
   "sanur": [
    "sanur",
    "sanúr",
    "sannur",
    "sanour",
    "sanurr",
    "semawang",
    "mertasari",
    "batu jimbar",
    "sindhu"
   ],
   "jimbaran": [
    "jimbaran",
    "jimbarán",
    "yimbaran",
    "jinbaran",
    "jimbaram",
    "jimberan",
    "kedonganan",
    "muaya",
    "ayana"
   ],
   "kuta_legian": [
    "kuta",
    "kutá",
    "legian",
    "leggian",
    "legean",
    "ligian",
    "tuban",
    "poppies",
    "waterbom",
    "beachwalk"
   ]
  },
  "group": {
   "couple": [
    "pareja",
    "novio",
    "novia",
    "marido",
    "esposa",
    "esposo",
    "mi mujer",
    "luna de miel",
    "aniversario",
    "romántic",
    "romantic",
    "recién casados",
    "recien casados",
    "viaje de novios",
    "somos dos",
    "somos 2"
   ],
   "family": [
    "familia",
    "hijo",
    "hija",
    "niño",
    "niña",
    "ninos",
    "bebé",
    "peques",
    "críos",
    "crios",
    "padres",
    "abuelos",
    "sobrinos",
    "nietos",
    "adolescente"
   ],
   "friends": [
    "amigo",
    "amiga",
    "colegas",
    "cuates",
    "pandilla",
    "despedida de soltero",
    "despedida de soltera",
    "en grupo",
    "un grupo de",
    "somos un grupo",
    "de chicas",
    "fiesta",
    "compañeros de viaje"
   ],
   "solo": [
    "viajo solo",
    "viajo sola",
    "viajar solo",
    "viajar sola",
    "voy solo",
    "voy sola",
    "en solitario",
    "por mi cuenta",
    "por libre",
    "sin compañía",
    "sin compania",
    "mochiler",
    "nómada digital",
    "nomada digital",
    "una persona",
    "solita",
    "solito"
   ]
  },
  "budget": {
   "low": [
    "barato",
    "barata",
    "económic",
    "economic",
    "asequible",
    "low cost",
    "lowcost",
    "presupuesto ajustado",
    "poco presupuesto",
    "presupuesto bajo",
    "gastar poco",
    "sin gastar mucho",
    "hostal",
    "hostel",
    "albergue",
    "ahorrar",
    "básico",
    "basico",
    "menos de 50"
   ],
   "mid": [
    "gama media",
    "rango medio",
    "nivel medio",
    "presupuesto medio",
    "precio medio",
    "calidad precio",
    "razonable",
    "moderado",
    "equilibrado",
    "3 estrellas",
    "tres estrellas",
    "4 estrellas",
    "cuatro estrellas",
    "cómodo",
    "comodo",
    "decente",
    "estándar",
    "estandar",
    "sin pasarme",
    "algo intermedio"
   ],
   "high": [
    "de lujo",
    "lujoso",
    "lujosa",
    "5 estrellas",
    "cinco estrellas",
    "premium",
    "exclusivo",
    "exclusiva",
    "alta gama",
    "primera clase",
    "villa privada",
    "chófer privado",
    "chofer privado",
    "sin límite de presupuesto",
    "sin limite de presupuesto",
    "no me importa gastar",
    "gastar lo que sea",
    "el dinero no es problema",
    "más de 120",
    "mas de 120"
   ]
  },
  "dayWords": [
   "dia",
   "día",
   "noche"
  ],
  "weekWords": [
   "dos semanas",
   "fin de semana",
   "semana",
   "semana y media",
   "una semana"
  ]
 },
 "ru": {
  "interests": {
   "sea": [
    "море",
    "моря",
    "морск",
    "пляж",
    "океан",
    "снорк",
    "дайв",
    "подводн",
    "плават",
    "плаван",
    "остров",
    "лодк",
    "яхт",
    "загорат",
    "гили",
    "пенида",
    "манта",
    "коралл"
   ],
   "nature": [
    "водопад",
    "джунгл",
    "вулкан",
    "батур",
    "агунг",
    "природ",
    "рисовы",
    "террас",
    "треккинг",
    "трекинг",
    "рассвет",
    "восход",
    "обезьян",
    "озер",
    "горы",
    "горах",
    "тегалаланг"
   ],
   "culture": [
    "храм",
    "культур",
    "традици",
    "церемони",
    "рынок",
    "рынк",
    "балийск",
    "аутентич",
    "деревн",
    "танцы",
    "кечак",
    "варунг",
    "кухн",
    "музей",
    "ритуал",
    "индуис",
    "танах",
    "колорит"
   ],
   "relax": [
    "релакс",
    "расслаб",
    "массаж",
    "спа-",
    "spa",
    "бассейн",
    "тишин",
    "спокойн",
    "ничего не делать",
    "полежать",
    "лениво",
    "чилл",
    "йога",
    "ретрит",
    "велнес",
    "перезагрузк",
    "выспат",
    "тихое место"
   ],
   "adventure": [
    "рафтинг",
    "квадроцикл",
    "квадрик",
    "atv",
    "серф",
    "сёрф",
    "адреналин",
    "экстрим",
    "экстремал",
    "банджи",
    "зиплайн",
    "каньонинг",
    "восхожден",
    "скалолаз",
    "параглайд",
    "внедорожн",
    "приключен",
    "активн",
    "кайт"
   ],
   "beauty": [
    "красив",
    "красот",
    "виды",
    "видом",
    "видами",
    "пейзаж",
    "панорам",
    "закат",
    "фото",
    "фотк",
    "инстаграм",
    "живопис",
    "смотров",
    "качели",
    "локаци",
    "эстетик",
    "картинк",
    "сторис"
   ]
  },
  "area": {
   "canggu": [
    "чангу",
    "чанггу",
    "cangu",
    "canggu",
    "changgu",
    "берава",
    "berawa",
    "переренан",
    "pererenan",
    "батубелиг",
    "batu belig",
    "эчо бич",
    "echo beach"
   ],
   "seminyak": [
    "семиньяк",
    "семиняк",
    "семинияк",
    "seminyak",
    "seminiak",
    "петитенгет",
    "petitenget",
    "дабл сикс",
    "double six",
    "оберой",
    "oberoi",
    "кробокан",
    "кероботокан",
    "kerobokan"
   ],
   "ubud": [
    "убуд",
    "ubud",
    "пенестанан",
    "penestanan",
    "чампуан",
    "кампухан",
    "campuhan",
    "сайан",
    "sayan",
    "монки форест",
    "monkey forest"
   ],
   "uluwatu": [
    "улувату",
    "uluwatu",
    "улуватту",
    "ulu watu",
    "бингин",
    "bingin",
    "паданг паданг",
    "padang padang",
    "сулубан",
    "suluban",
    "пекату",
    "pecatu",
    "дримленд",
    "dreamland",
    "меласти",
    "melasti",
    "унгасан",
    "ungasan"
   ],
   "nusa_dua": [
    "нуса дуа",
    "нуса-дуа",
    "нусадуа",
    "nusa dua",
    "nusa-dua",
    "nusadua",
    "танджунг беноа",
    "tanjung benoa",
    "беноа",
    "benoa",
    "гегер",
    "geger"
   ],
   "sanur": [
    "санур",
    "sanur",
    "мертасари",
    "mertasari",
    "синдху",
    "sindhu",
    "серанган",
    "serangan",
    "матахари тербит",
    "matahari terbit"
   ],
   "jimbaran": [
    "джимбар",
    "жимбар",
    "jimbar",
    "кедонганан",
    "kedonganan",
    "муая",
    "muaya",
    "аяна",
    "ayana"
   ],
   "kuta_legian": [
    "кута",
    "куте",
    "куты",
    "kuta",
    "легиан",
    "legian",
    "легьян",
    "тубан",
    "tuban",
    "вотербом",
    "waterbom"
   ]
  },
  "group": {
   "couple": [
    "двоем",
    "двоём",
    "с женой",
    "с мужем",
    "с девушкой",
    "с парнем",
    "с любимой",
    "с любимым",
    "романти",
    "медовый месяц",
    "молодожен",
    "молодожён",
    "годовщин",
    "нас двое",
    "вторая половинк",
    "мы пара",
    "с супруг",
    "свадебное путешествие"
   ],
   "family": [
    "детьми",
    "детей",
    "ребенк",
    "ребёнк",
    "дети",
    "детск",
    "с сыном",
    "с дочк",
    "малыш",
    "коляск",
    "подростк",
    "семьей",
    "семьёй",
    "семья",
    "семейн",
    "с родителями",
    "с мамой",
    "с бабушкой"
   ],
   "friends": [
    "друзья",
    "друзей",
    "подругой",
    "подругами",
    "компанией",
    "вчетвером",
    "впятером",
    "вшестером",
    "тусов",
    "вечеринк",
    "мальчишник",
    "девичник",
    "с коллегами",
    "с парнями",
    "с девчонками",
    "нас четверо"
   ],
   "solo": [
    "соло",
    "solo",
    "одиночк",
    "одному",
    "еду один",
    "еду одна",
    "поеду один",
    "поеду одна",
    "лечу один",
    "лечу одна",
    "я один",
    "я одна",
    "только я",
    "сам по себе",
    "сама по себе",
    "без компании",
    "один человек",
    "путешествую один"
   ]
  },
  "budget": {
   "low": [
    "бюджетн",
    "дешев",
    "дёшев",
    "недорог",
    "эконом",
    "хостел",
    "гестхаус",
    "гостевой дом",
    "скромн",
    "бэкпек",
    "мало денег",
    "ограниченный бюджет",
    "до 50 долларов",
    "до 50$",
    "меньше 50 долларов",
    "без излишеств",
    "простое жилье"
   ],
   "mid": [
    "средн",
    "комфорт",
    "золотая середина",
    "оптимальн",
    "разумн",
    "адекватн",
    "нормальн",
    "умеренн",
    "приличн",
    "3 звезды",
    "три звезды",
    "4 звезды",
    "четыре звезды",
    "50-120",
    "до 120 долларов",
    "100 долларов"
   ],
   "high": [
    "люкс",
    "лакшери",
    "luxury",
    "роскош",
    "премиум",
    "премиальн",
    "элитн",
    "шикарн",
    "5 звезд",
    "пять звезд",
    "инфинити",
    "четыре сезона",
    "four seasons",
    "от 150 долларов",
    "200 долларов",
    "бюджет не ограничен",
    "все включено",
    "всё включено"
   ]
  },
  "dayWords": [
   "день",
   "дней",
   "дня",
   "несколько дней",
   "пару дней",
   "сутки"
  ],
  "weekWords": [
   "две недели",
   "недели",
   "неделю",
   "неделя",
   "полторы недели"
  ]
 },
 "fr": {
  "interests": {
   "sea": [
    "plage",
    "la mer",
    "bord de mer",
    "océan",
    "ocean",
    "baignade",
    "baigner",
    "sable blanc",
    "snorkel",
    "masque et tuba",
    "plong",
    "corail",
    "tortue",
    "bateau",
    "croisière",
    "croisiere",
    "île",
    "nusa penida",
    "gili",
    "eau turquoise"
   ],
   "nature": [
    "cascade",
    "rizière",
    "riziere",
    "terrasses de riz",
    "jungle",
    "forêt tropicale",
    "foret tropicale",
    "volcan",
    "batur",
    "kintamani",
    "montagne",
    "rando",
    "trek",
    "lever de soleil",
    "lever du soleil",
    "tegalalang",
    "jatiluwih",
    "la nature",
    "pleine nature",
    "nature sauvage"
   ],
   "culture": [
    "temples",
    "temple hindou",
    "tanah lot",
    "besakih",
    "tirta empul",
    "cérémonie",
    "ceremonie",
    "offrande",
    "hindou",
    "tradition",
    "authentique",
    "marché local",
    "marchés locaux",
    "artisanat",
    "danse balinaise",
    "kecak",
    "warung",
    "cuisine locale",
    "vie locale",
    "village balinais"
   ],
   "relax": [
    "massage",
    "spa balinais",
    "un spa",
    "le spa",
    "détente",
    "detente",
    "détendre",
    "detendre",
    "farniente",
    "rien faire",
    "piscine",
    "tranquil",
    "calme",
    "repos",
    "yoga",
    "méditation",
    "meditation",
    "zen",
    "chill",
    "cocooning"
   ],
   "adventure": [
    "aventure",
    "adrénaline",
    "adrenaline",
    "rafting",
    "du surf",
    "surfe",
    "surfing",
    "cours de surf",
    "quad",
    "atv",
    "buggy",
    "tyrolienne",
    "escalade",
    "canyoning",
    "vtt",
    "jet ski",
    "jetski",
    "hors piste",
    "sensations fortes",
    "parapente"
   ],
   "beauty": [
    "paysage",
    "magnifique",
    "sublime",
    "superbe",
    "splendide",
    "belle vue",
    "vue imprenable",
    "panorama",
    "point de vue",
    "coucher de soleil",
    "coucher du soleil",
    "couché de soleil",
    "sunset",
    "photo",
    "instagram",
    "carte postale",
    "couper le souffle",
    "joli",
    "belle",
    "de rêve"
   ]
  },
  "area": {
   "canggu": [
    "canggu",
    "cangu",
    "canggou",
    "changgu",
    "changu",
    "kanggu",
    "kangu",
    "berawa",
    "pererenan",
    "batu bolong",
    "echo beach",
    "tibubeneng",
    "seseh"
   ],
   "seminyak": [
    "seminyak",
    "seminyack",
    "seminiak",
    "séminyak",
    "semynak",
    "seminyk",
    "petitenget",
    "kerobokan",
    "batu belig",
    "umalas",
    "double six",
    "oberoi"
   ],
   "ubud": [
    "ubud",
    "oubud",
    "obud",
    "ubod",
    "uboud",
    "monkey forest",
    "foret des singes",
    "forêt des singes",
    "campuhan",
    "penestanan",
    "goa gajah"
   ],
   "uluwatu": [
    "uluwatu",
    "ulu watu",
    "uluwattu",
    "ulluwatu",
    "oulouwatou",
    "bukit",
    "padang padang",
    "bingin",
    "pecatu",
    "suluban",
    "dreamland",
    "balangan"
   ],
   "nusa_dua": [
    "nusa dua",
    "nusadua",
    "nusa-dua",
    "nusa doua",
    "noussa doua",
    "benoa",
    "bualu",
    "sawangan",
    "geger",
    "btdc",
    "water blow"
   ],
   "sanur": [
    "sanur",
    "sanour",
    "sannur",
    "sanoor",
    "sanoure",
    "semawang",
    "mertasari",
    "batu jimbar",
    "sindhu"
   ],
   "jimbaran": [
    "jimbaran",
    "jimbarran",
    "jimbaram",
    "jimbran",
    "jinbaran",
    "djimbaran",
    "jimbaren",
    "kedonganan",
    "muaya"
   ],
   "kuta_legian": [
    "kuta",
    "kouta",
    "koutta",
    "kutta",
    "legian",
    "légian",
    "legyan",
    "ligian",
    "poppies",
    "waterbom",
    "beachwalk"
   ]
  },
  "group": {
   "couple": [
    "couple",
    "amoureux",
    "lune de miel",
    "voyage de noces",
    "jeunes mariés",
    "jeunes maries",
    "ma copine",
    "mon copain",
    "ma femme",
    "mon mari",
    "ma compagne",
    "mon compagnon",
    "mon époux",
    "mon epoux",
    "romantique",
    "nous deux",
    "tous les deux",
    "voyage à deux",
    "voyage a deux"
   ],
   "family": [
    "famille",
    "familial",
    "enfant",
    "bébé",
    "bebe",
    "ma fille",
    "mes filles",
    "mon fils",
    "mes fils",
    "kids",
    "gamins",
    "ados",
    "adolescent",
    "mes parents",
    "grands-parents",
    "poussette",
    "bambin"
   ],
   "friends": [
    "amis",
    "potes",
    "copains",
    "copines",
    "entre filles",
    "entre mecs",
    "en groupe",
    "notre groupe",
    "collègues",
    "collegues",
    "evjf",
    "evg"
   ],
   "solo": [
    "solo",
    "tout seul",
    "toute seule",
    "je pars seul",
    "je pars seule",
    "je voyage seul",
    "je voyage seule",
    "je suis seul",
    "solitaire",
    "célibataire",
    "celibataire",
    "juste moi"
   ]
  },
  "budget": {
   "low": [
    "pas cher",
    "moins cher",
    "petit budget",
    "budget serré",
    "budget serre",
    "budget limité",
    "budget limite",
    "économique",
    "economique",
    "bon marché",
    "bon marche",
    "backpacker",
    "routard",
    "auberge de jeunesse",
    "guesthouse",
    "homestay",
    "low cost",
    "petit prix",
    "sans se ruiner",
    "moins de 50"
   ],
   "mid": [
    "milieu de gamme",
    "moyenne gamme",
    "budget moyen",
    "raisonnable",
    "qualité prix",
    "qualite prix",
    "3 étoiles",
    "3 etoiles",
    "trois étoiles",
    "trois etoiles",
    "pas trop cher",
    "ni trop cher",
    "hôtel confortable",
    "hotel confortable",
    "budget correct",
    "standing correct",
    "entre 50 et 120"
   ],
   "high": [
    "luxe",
    "luxueux",
    "haut de gamme",
    "5 étoiles",
    "5 etoiles",
    "cinq étoiles",
    "cinq etoiles",
    "palace",
    "premium",
    "prestige",
    "villa privée",
    "villa privee",
    "gros budget",
    "budget illimité",
    "budget illimite",
    "grand confort",
    "grand standing",
    "plus de 120"
   ]
  },
  "dayWords": [
   "journee",
   "journée",
   "jours",
   "nuit",
   "nuitee",
   "nuitée"
  ],
  "weekWords": [
   "semaine",
   "week-end",
   "weekend"
  ]
 },
 "de": {
  "interests": {
   "sea": [
    "strand",
    "strände",
    "meer",
    "schnorchel",
    "tauchen",
    "schwimmen",
    "baden",
    "badeurlaub",
    "insel",
    "korallenriff",
    "bootstour",
    "bootsfahrt",
    "delfin",
    "delphin",
    "gili",
    "penida"
   ],
   "nature": [
    "wasserfall",
    "wasserfäll",
    "reisterrass",
    "reisfeld",
    "dschungel",
    "urwald",
    "regenwald",
    "vulkan",
    "krater",
    "batur",
    "natur",
    "wander",
    "sonnenaufgang",
    "affenwald",
    "monkey forest",
    "tegalalang"
   ],
   "culture": [
    "tempel",
    "kultur",
    "zeremoni",
    "tradition",
    "markt",
    "märkte",
    "einheimisch",
    "balines",
    "hindu",
    "kecak",
    "tänze",
    "opfergabe",
    "warung",
    "authentisch",
    "museum",
    "kunsthandwerk"
   ],
   "relax": [
    "entspann",
    "erholen",
    "erholung",
    "wellness",
    "massage",
    "ruhe",
    "ruhig",
    "faulenzen",
    "nichts tun",
    "nichtstun",
    "pool",
    "ausspannen",
    "seele baumeln",
    "abschalten",
    "yoga",
    "chillen",
    "auszeit",
    "ausschlafen",
    "meditation"
   ],
   "adventure": [
    "rafting",
    "wildwasser",
    "surf",
    "wellenreiten",
    "klettern",
    "adrenalin",
    "abenteuer",
    "nervenkitzel",
    "canyoning",
    "bungee",
    "ziplin",
    "offroad",
    "off road",
    "quad",
    "atv-tour",
    "atv fahren",
    "action",
    "mountainbike",
    "paraglid"
   ],
   "beauty": [
    "aussicht",
    "ausblick",
    "landschaft",
    "panorama",
    "foto",
    "instagram",
    "sonnenuntergang",
    "sunset",
    "malerisch",
    "atemberaubend",
    "traumhaft",
    "postkarte",
    "kulisse",
    "wunderschön",
    "idyllisch",
    "spektakulär"
   ]
  },
  "area": {
   "canggu": [
    "canggu",
    "cangu",
    "canngu",
    "changgu",
    "changu",
    "kanggu",
    "tschanggu",
    "berawa",
    "brawa",
    "pererenan",
    "batu bolong",
    "echo beach"
   ],
   "seminyak": [
    "seminyak",
    "seminjak",
    "seminiak",
    "semynak",
    "seminyk",
    "seminak",
    "semiyak",
    "petitenget",
    "oberoi",
    "kayu aya",
    "batu belig"
   ],
   "ubud": [
    "ubud",
    "ubod",
    "ubut",
    "ubuud",
    "ubbud",
    "obud",
    "campuhan",
    "penestanan",
    "kedewatan",
    "sayan",
    "nyuh kuning",
    "künstlerdorf"
   ],
   "uluwatu": [
    "uluwatu",
    "ulu watu",
    "uluwato",
    "uluwattu",
    "ulluwatu",
    "ulawatu",
    "bukit",
    "pecatu",
    "ungasan",
    "bingin",
    "padang padang",
    "balangan",
    "dreamland",
    "suluban"
   ],
   "nusa_dua": [
    "nusa dua",
    "nusadua",
    "nusa-dua",
    "nusa duo",
    "nussa dua",
    "nusa dhua",
    "tanjung benoa",
    "benoa",
    "geger",
    "sawangan",
    "bualu"
   ],
   "sanur": [
    "sanur",
    "sanor",
    "sannur",
    "sanoer",
    "sanuur",
    "sanurr",
    "sindhu",
    "mertasari",
    "semawang"
   ],
   "jimbaran": [
    "jimbaran",
    "jimbaram",
    "jimbarn",
    "jimberan",
    "jimbahran",
    "gimbaran",
    "dschimbaran",
    "kedonganan",
    "muaya"
   ],
   "kuta_legian": [
    "kuta",
    "kutta",
    "legian",
    "legien",
    "legain",
    "ligian",
    "legiaan",
    "tuban",
    "waterbom",
    "poppies",
    "beachwalk"
   ]
  },
  "group": {
   "couple": [
    "zu zweit",
    "als paar",
    "pärchen",
    "mein freund",
    "meinem freund",
    "meine freundin",
    "meiner freundin",
    "meine frau",
    "mein mann",
    "ehemann",
    "ehefrau",
    "partner",
    "verlobte",
    "flitterwochen",
    "hochzeitsreise",
    "honeymoon",
    "romantisch",
    "romantik",
    "zweisamkeit",
    "wir beide"
   ],
   "family": [
    "familie",
    "kind",
    "kids",
    "baby",
    "sohn",
    "tochter",
    "eltern",
    "nachwuchs",
    "mama",
    "mit den kleinen"
   ],
   "friends": [
    "freunde",
    "freundinnen",
    "kumpel",
    "jungs",
    "mädels",
    "gruppe",
    "clique",
    "zu dritt",
    "zu viert",
    "zu fünft",
    "männertrip",
    "mädelstrip",
    "junggesellenabschied",
    "junggesellinnenabschied",
    "mit kollegen",
    "party",
    "feiern"
   ],
   "solo": [
    "allein",
    "alleine",
    "alleinreisend",
    "solo",
    "soloreise",
    "solotrip",
    "einzelzimmer",
    "nur ich",
    "ohne begleitung",
    "als single",
    "auf eigene faust"
   ]
  },
  "budget": {
   "low": [
    "günstig",
    "billig",
    "preiswert",
    "sparen",
    "sparsam",
    "low budget",
    "kleines budget",
    "knappes budget",
    "schmales budget",
    "wenig geld",
    "backpacker",
    "hostel",
    "homestay",
    "unter 50",
    "weniger als 50",
    "maximal 50",
    "höchstens 50",
    "einfache unterkunft",
    "nicht viel ausgeben"
   ],
   "mid": [
    "mittelklasse",
    "mittleres budget",
    "mittelpreisig",
    "mittleres preissegment",
    "preis-leistung",
    "nicht zu teuer",
    "guter standard",
    "moderate preise",
    "vernünftiger preis",
    "3 sterne",
    "drei sterne",
    "normales budget",
    "um die 100",
    "bis 120",
    "50 bis 120",
    "50-120"
   ],
   "high": [
    "luxus",
    "luxuriös",
    "5 sterne",
    "fünf sterne",
    "gehoben",
    "exklusiv",
    "erstklassig",
    "premium",
    "high end",
    "privatvilla",
    "edel",
    "nobelhotel",
    "geld spielt keine rolle",
    "über 120",
    "ab 150",
    "200 dollar",
    "verwöhnprogramm"
   ]
  },
  "dayWords": [
   "nacht",
   "tage",
   "vierzehn tage",
   "zehn tage",
   "übernachtung"
  ],
  "weekWords": [
   "anderthalb wochen",
   "drei wochen",
   "eine woche",
   "woche",
   "wochen",
   "wochenende",
   "zwei wochen"
  ]
 }
};
